### PR TITLE
Branch1

### PR DESCRIPTION
**Pull request by 01-DC**
Fix logo position and style in welcome page.
Fixed some errors in code.

### CODE REVIEW

**Review by NeerajHazarika — APPROVED** [review]
Noice

**Comment by NeerajHazarika** [comment]
@01-DC could u make the logo as it was before, i dont wanna keep it at the left corner

**Comment by NeerajHazarika** [comment]
image
and it's buggy when i make the window smaller

**Comment by 01-DC** [comment]
Okay. I am on it.

**Comment by 01-DC** [comment]
You add the images till then.

**Comment by NeerajHazarika** [comment]
Kool

**Pull request merged**
